apiVersion: batch/v1
kind: Job
metadata:
  generateName: order-api-springboot-functional-test-
  labels:
    app: order-api-springboot
    role: functional-test-run
spec:
  backoffLimit: 0
  template:
    metadata:
      labels:
        app: order-api-springboot
        role: functional-test-run
    spec:
      restartPolicy: Never
      containers:
        - name: functional-tests
          image: order-api-springboot-functional-tests:latest
          env:
            - name: ORDERAPI_BASE_URL
              value: http://order-api-springboot:8080
